### ISSUE TITLE
Add (or document) ability to pull older versions of dependent buildpacks

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/occam#183]
## Describe the Enhancement

I am trying to iterate on the integration between Buildpack B (e.g. `pip`) and its dependency, buildpack A (e.g. `cpython`). 

Specifically, the integration tests for Buildpack B are failing with the current version of Buildpack A. I want to run the integration tests for Buildpack B with the previous version of Buildpack A - which is available on github and dockerhub - but I can't figure out how to provide the URL to the previous version of Buildpack A from either GitHub or dockerhub.

I took a quick look through the code and I don't think this is possible, but if it exists then I think this is a documentation issue, not a feature request.

**Comment by sophiewigmore** [comment]
I'm not entirely sure that that's possible, but you can pull the older buildpack version locally and then plug that into the buildpack. We should document that at least.

**Comment by fg-j** [comment]
To do this, I'd probably modify the [`pack.Build.WithBuildpacks()`](https://github.com/paketo-buildpacks/occam/blob/e942e373097b52513dcec9301b683a2845258aa5/pack.go#L86) for a given integration test to use the URI of the previous version of Buildpack A instead of the string that `freezer.BuildpackStore.Get()` produces as output. Like, swap out a hard-coded URI [in here](https://github.com/paketo-buildpacks/pip-install/blob/9d66e9b2544a353119a7ea40fdee85cf4c789823/integration/default_test.go#L62) for instance. You'll need to pre-pull that tag before the test runs so `WithPullPolicy("never")` still works. Does that address the use case? Or are you trying to _programmatically_ determine "the previous version" of the buildpack?

**Comment by robdimsdale** [comment]
Ah, ok, so bypass freezer entirely. That works, thanks @fg-j !

I wasn't trying to do anything programmatically - just trying to compare the integration against two known versions of a dependent buildpack.

**Comment by robdimsdale** [comment]
I'll close this conversation as we can use this issue as a source of record for anyone trying to do this in the future. I'm not sure we need to add it to the documentation.
